const firstFakeUserAccessToken = 'CAAPNND0M4h8BABLVB2LghSLvb838eJkHlvODZCrEsESXeNynAqlqsnTvz6n6CgyMZBP8TrF7rh3v3y14bmy8JNxmDgZAYGvWZC8mDuo3QE9B8QwwyLQFsKpAyIiWZBEffnqfJGorz4wHlOtYSpqD2AhXUVZAnmPut38SmG6veGJjt74tGyJClNZCalZBEiT9qZBNwIBkGMjFfzKFcdrX6Bo6W'

const secondFakeUserAccessToken = 'CAAPNND0M4h8BAHsswevp5xBTuwiQ1qy1ZCT2PwJOw1icfysJWC5uzGaZAgUJi7enkZBVsvm0HVUZBw9KkF5QziZAV59erb57MPZBpOzezZCekrVG3XDTwWQtOWuBCOccZBWTE9goaZCoyqpdo6KzaYQgLLyZBW6BXaZCl2ZAjnZCTpEJbMUDPRREKju6IWjGfxygqZC7rGXzZBdvz55ZBHCuF5VhiJIO'

exports.firstFakeUserToken = () => {
    return firstFakeUserAccessToken
}

exports.secondFakeUserToken = () => {
    return secondFakeUserAccessToken
}
